apiVersion: batch/v1
kind: Job
metadata:
  name: jobs_prac
spec:
  template:
    spec:
      containers:
        - name: job_practice
          image: busybox
          command:
            - "echo"
            - "Hello Kubernetes!!!"
      restartPolicy: Never