apiVersion: batch/v1
kind: Job
metadata:
  name: job_prac
spec:
  template:
    spec:
      containers:
        - name: job_practice
          image: busybox
          command:
            - "sleep"
            - "60"