apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: nginx-frontend
    stage: testing
spec:
  template:
    metadata:
      name: frontend-app
      labels:
        app: nginx-frontend
        stage: testing
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: nginx-frontend
      stage: testing

