apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels:
    app: volume-pod
spec:
  volumes:
    - name: host-volume
      hostPath:
        path: /home/docker/volume
#       Current host is minikube VM, so dont use your host directory but use minikube's directory
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: host-volume
    - name: debian
      image: debian
      volumeMounts:
        - mountPath: /host-vol
          name: host-volume
      command: ["/bin/sh","-c","echo Introduction to Kubernetes > /host-vol/index.html; sleep 3600"]