apiVersion: v1
kind: Pod
metadata:
  name: volume-test-pod
  labels:
    app: volume-test-pod
spec:
  volumes:
    - name: check-volume
      hostPath:
        path: /home/docker/volume
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: check-volume
      ports:
        - containerPort: 80