apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-tolerations
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      name: app-no-toleration
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
  replicas: 2
