# Create a deployment

apiVersion: apps/v1
# kind is Deployemnt and rest is same as 
kind: Deployment
metadata:
  name: my-deployment-app
  labels:
    app: my-app
    type: frontend
    stage: deployment
spec:
  template:
    metadata:
      name: my-app
      labels:
        type: frontend
        stage: deployment 
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      type: frontend
      stage: deployment

# View the deployments
# kubectl get deployment